LOCK TABLES `solution` WRITE;
INSERT INTO `solution` VALUES 
(1,1,'2020-06-16 12:08:31',0,'Risk Engine','Solution for internal users to be able to process settlement for FX transactions','XXX-123-456-YYY','Jenkins','Spinnaker','GitHub',1,'SUCCESS',200,'200','Solution deployment updated.','MOCKTASKID5',1,'MOCKFOLDERID5',1),
(2,1,'2020-03-08 23:07:00',0,'Back Office Settlements','Solution for internal users to be able to process settlement for FX transactions','XXX-111-444-YYY','Jenkins','Spinnaker','GitHub',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(3,1,'2020-03-08 23:07:00',0,'FX Engine','Solution for internal users to be able to process settlement for FX transactions','XXX-554-325-YYY','Jenkins','Spinnaker','GitHub',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(4,1,'2020-03-18 21:02:02',1,'Portfolio Valuation','A portfolio valuation is done to determine and report alternative investments\' performance, which is often required for financial reporting and tax compliance.','XXX-333-222-IUY','Bamboo','Screwdriver','Cloud native',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(5,1,'2020-03-18 21:13:14',1,'Corporate Treasury','The treasury department occupies a central role in the finances of the modern corporation.','XXX-333-222-IUY','Team City','Team City','GitHub',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(6,1,'2020-03-18 21:15:22',1,'Internal Audit','Internal auditing is the independent and objective evaluation of an organisation\'s internal controls to effectively manage risk.','XXX-333-222-IUY','Travis','Screwdriver','Cloud native',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(7,1,'2020-03-18 21:19:58',1,'Realtime Margin','Use real-time margin monitoring to see your current margin requirements at a glance, and to understand the margin implications of any transaction before you transmit an order.','ABC-123-ABC-123','Cloud native','Spinnaker','Cloud native',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(8,1,'2020-03-18 21:25:10',1,'Product Control','Product control are a center of cost responsible for the daily PnL(Profit and Loss) and its explanation for a dedicated trading desk. The team is responsible to communicate this result within the bank and to the authority FED or ECB.','dat-000-ser-322','Bamboo','Screwdriver','BitBucket',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(9,1,'2020-03-18 21:43:54',1,'General Ledger','A general ledger (GL) is a set of numbered accounts a business uses to keep track of its financial transactions and to prepare financial reports.','ldf-343-sds-232','Cloud native','Team City','Cloud native',0,'',NULL,NULL,NULL,NULL,1,NULL,1),
(10,1,'2020-03-19 23:41:59',1,'Corporate Finance','Corporate finance is the division of finance that deals with financing, capital structuring, and investment decisions.','ASD-456-FFH-234','Bamboo','Screwdriver','Cloud native',0,'',NULL,NULL,NULL,NULL,1,NULL,1);
UNLOCK TABLES;
