version: '3.1'

services:
  mysql57:
    image: gcr.io/eagle-console-resources/tb-houston-mysql57:mock
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: eagle-user
      MYSQL_PASSWORD: eagle-user-secret-pw
      MYSQL_DATABASE: eagle_db
    ports:
    - '3306:3306'